## Laboratorio Arreglos y Matrices


Ejecuta la celda de abajo para cargar los paquetes requeridos

In [2]:
import numpy as np
import pandas as pd

### Datos de ventas

Para este lab vamos a estar usando una versión de datos de ventas de vinos en diferentes sucursales (archivo ```volumen_ventas_producto_sucursal.csv```) y el precio de cada vino (```precio_producto.csv```)

#### Importar Ventas

In [23]:
sales = pd.read_csv('volumen_ventas_producto_sucursal.csv')
sales.head(10)

producto  Sucursal 1  Sucursal 2  Sucursal 3  Sucursal 4  Sucursal 5  \
0         Malbec         429         106         437         177         200   
1       Cabernet         244         111         282         238         144   
2          Syrah         374         278         241         408         177   
3  Caberne Franc         449         291         461         484         452   
4         Merlot         222         494         436         252         161   
5     Pinot noir         335         137         233         487         394   

   Sucursal 6  Sucursal 7  
0         412         309  
1         198         331  
2         381         237  
3         388         466  
4         187         337  
5         488         331

#### Importar precios

In [7]:
precios = pd.read_csv('precio_producto.csv')
precios.head()

producto  Precio
0         Malbec     208
1       Cabernet     216
2          Syrah     247
3  Caberne Franc     180
4         Merlot     180

#### 1. Calcular la cantidad de unidades vendidas para cada sucursal

Utilizar la matriz_ventas y funciones de numpy
Primero transformar el dataframe de pandas en un array con las funciones iloc y values

In [19]:
ventas_np = sales.iloc[:,1:].values

In [20]:
#acá código
ventas_por_sucursal = ventas_np.sum(axis=0)
ventas_por_sucursal

array([2053, 1417, 2090, 2046, 1528, 2054, 2011], dtype=int64)

#### 2. Calcular la cantidad de unidades vendidas para cada producto

Utilizar la matriz_ventas y funciones de numpy

In [21]:
#acá código
ventas_por_producto = ventas_np.sum(axis=1)
ventas_por_producto

array([2070, 1548, 2096, 2991, 2089, 2405], dtype=int64)

#### 3. Calcular cuál es el producto que más vendió cada sucursal


In [40]:
print(ventas_np.shape)
ventas_np

(6L, 7L)


array([[429, 106, 437, 177, 200, 412, 309],
       [244, 111, 282, 238, 144, 198, 331],
       [374, 278, 241, 408, 177, 381, 237],
       [449, 291, 461, 484, 452, 388, 466],
       [222, 494, 436, 252, 161, 187, 337],
       [335, 137, 233, 487, 394, 488, 331]], dtype=int64)

In [43]:
np.argmax(ventas_np, axis=0)

array([3, 4, 3, 5, 3, 5, 3], dtype=int64)

In [45]:
#acá código
max_ventas = np.argmax(ventas_np, axis=0)
vinos = np.array(['M', 'C', 'S', 'CF','M','PN'])
print ("Vinos más vendidos:")
vinos[max_ventas ]

# Combino los dos vectores en un arary de una dimensión más.
print (np.array([vinos,vinos[max_ventas ]]))

Vinos más vendidos:


array(['CF', 'M', 'CF', 'PN', 'CF', 'PN', 'CF'], 
      dtype='|S2')

#### 4. Calcular cuál es la sucursal que más vendió cada producto


In [48]:
#acá código
max_ventas = np.argmax(ventas_np, axis=1)
sucursales = np.array(['S1', 'S2', 'S3', 'S4','S5','S6','S7'])
print ("Sucursal que más vendió:")
sucursales[max_ventas ]

# Combino los dos vectores en un arary de una dimensión más.
print (np.array([vinos,sucursales[max_ventas ]]))

Sucursal que más vendió:
[['M' 'C' 'S' 'CF' 'M' 'PN']
 ['S3' 'S7' 'S4' 'S4' 'S2' 'S6']]


#### 5. Calcular la facturación para cada sucursal

Utilizando multiplicación matricial (matriz_ventas, matriz_precios) obtener la facturación para cada sucursal (es decir la sumatoria de cantidad vendidada * precio para cada producto).

Nota: Se deberá utilizar la función matriz.transpose() para poder realizar la multiplicación matricial, dado que dos matrices A de forma (p,q) y B de forma (r,s) solo se puede multplicar si q=r


In [46]:
#código acá
precios_np = precios.iloc[:,1]
precios_np.transpose().dot(ventas_np)

array([436499, 289281, 429414, 439821, 322505, 444655, 419280], dtype=int64)